# -*- coding: utf-8 -*-
"""DecisionTree_HeartDisease.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mbq_vjWHwVovQ3RA9fM2B6fzUBTj2HH2
"""

# import library skicit untuk fungsi Decision tree nya, dan pandas as pd untuk import dataset, dan matplotlib.pyplot as plt untuk gambar grafiknya
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import matplotlib.pyplot as plt

#load data set nya yaitu Heart_disease_cleveland_new.csv
# memilih atribute yang akan digunakan yaitu membuat variabel bernama features yang diisikan dengan sintax data.iloc[:, 0:13] berarti memilih index kolom dari 0-12 dari dataset
# memilih label atau class dengan membuat variable baru bernama target disikan dengan sintax data.iloc[-1] berarti memilih index terakhir dari dataset
data = pd.read_csv('Heart_disease_cleveland_new.csv')
features = data.iloc[:, 0:13]
target = data.iloc[:, -1]

#membuat objek model DecisionTree
decisiontree =  DecisionTreeClassifier(random_state=0, max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0, max_leaf_nodes=None, min_impurity_decrease=0)

# men training model Decision Tree
  model = decisiontree.fit(features, target)

observation = [[14,13,12,11,10,9,8,7,6,5,4,3,2]]
model.predict(observation)
model.predict_proba(observation)

import pydotplus
from sklearn import tree
target = target.astype(str)
dot_data = tree.export_graphviz(model, out_file=None, feature_names=features.columns, class_names=target.unique())

from IPython.display import Image
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_png('hasil.png')